name: 'install-docker'
description:  'Installs docker'
inputs:
    env_file:
        description: 'The path to the environment file'
        required: true
runs:
    using: 'composite'
    steps:
        - name: Install Docker
          shell: bash
          run: |
            source ${{ inputs.env_file }}
            echo "Installing docker - version ${VER_DOCKER_MAX}..."
            echo ""
            echo "perform get update and install ca-certificates and curl"
            sudo apt-get update
            sudo apt-get install ca-certificates curl

            echo "Adding Docker GPG key..."
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc

            echo "Adding Docker repository to apt sources..."
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "${VER_DOCKER_MAX}") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update

            echo "Installing Docker-ce, Docker-ce-cli, Containerd.io, Docker-buildx-plugin, Docker-compose-plugin"
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

            echo "Setup docker group"
            sudo usermod -aG docker $USER 
            echo "Runnning hello-world"
            docker run hello-world 
            echo "Get Version"
            docker version

            echo "Performing hello-world test..."
            sudo docker run hello-world

            echo "Making docker sudo-less..."
            sudo usermod -aG docker $USER
            newgrp docker
            docker run hello-world