name: 'install-dev-container-cli'
description:  'Installs the devcontainer cli'
runs:
    using: 'composite'
    steps:
        - name: Install Devcontainer cli
          shell: bash
          run: |
            echo "Detecting architecture..."
            TARGET_ARCHITECTURE="amd64"
            ARCH=$(uname -m)

            if [[ "$ARCH" == "x86_64" ]]; then
              echo "amd64 architecture detected"
              echo "Installing npm.."
              sudo apt-get install npm
              echo ""
              echo "Running npm cache clean -f..."
              sudo npm cache clean -f
              echo "Running npm install -g n..."
              sudo npm install -g n
              echo "Running npm install -g @devcontainers/cli..."
              sudo npm install -g @devcontainers/cli
            elif [[ "$ARCH" == "aarch64" ]]; then
                echo "arm64 architecture detected"
                if ! command -v npm &> /dev/null
                then
                  echo "npm is not installed, installing..."
                  sudo apt-get update
                  echo "installing npm..."
                  sudo apt-get install -y npm
                  echo ""
                  echo "Checking the version..."
                  npm --version
                  echo "Running 'npm cache clean -f'..."
                  sudo npm cache clean -f
                  echo ""
                  echo "Setup the directory...."
                  sudo mkdir -p /usr/local/lib/node_modules
                  sudo chown -R $USER:$USER /usr/local/lib/node_modules
                  echo ""
                  echo "Setting up permissions"
                  mkdir ~/.npm-global
                  npm config set prefix '~/.npm-global'
                  echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.bashrc
                  source ~/.bashrc
                fi

                echo "Runnning 'npm install -g n'..."
                sudo npm install -g n
                # echo "Runnning 'n stable'..."
                # sudo n stable
                echo "Runnning 'npm install -g @devcontainers/cli'..."
                sudo npm install -g @devcontainers/cli
                echo "Checking the version..."
                devcontainer --version
                printenv
            else
                echo "Unknown architecture: $ARCH"
                exit 1
            fi
            
            
