name: 'install-dev-container-cli'
description:  'Installs the devcontainer cli'
runs:
    using: 'composite'
    steps:
        - name: Install Devcontainer cli
          shell: bash
          run: |
            # echo "Installing npm.."
            # sudo apt-get install npm
            # echo ""
            # echo "Running npm cache clean -f..."
            # sudo npm cache clean -f
            # echo "Running npm install -g n..."
            # sudo npm install -g n
            # echo "Running n stable..."
            # sudo n stable
            # echo "Running npm install -g @devcontainers/cli..."
            # sudo npm install -g @devcontainers/cli

            if ! command -v npm &> /dev/null
            then
                echo "npm is not installed, installing..."
                sudo apt-get update
                sudo apt-get install -y npm
                echo "Setting permissions for directories..."

                NPM_DIR_PATH=$(find ~ -name ".npm" -type d 2>/dev/null)
                echo "Path of .npm directory: $NPM_DIR_PATH"

                sudo chown -R `whoami` $NPM_DIR_PATH
                sudo chown -R `whoami` /usr/local/lib/node_modules
            else
                echo "npm is installed"
            fi
            sudo npm cache clean -f
            sudo npm install -g n
            sudo n stable
            npm install -g @devcontainers/cli
            devcontainer --version
            printenv
            
