name: 'install-dev-container-cli'
description:  'Installs the devcontainer cli'
runs:
    using: 'composite'
    steps:
        - name: Install Devcontainer cli
          shell: bash
          run: |
            sudo apt install npm
            sudo npm cache clean -f
            sudo npm install -g n
            sudo n stable
            sudo npm install -g @devcontainers/cli
            
