name: 'stand-up-dev-container'
description:  'This stands up the devcontainer'
inputs:
    registry_name:
        description: 'The name of the registry'
        default: 'ghcr.io/microsoft'
    github-user-name:
        description: 'The name of the github user'
        required: true
    github-user-token:
        description: 'The token to use for the registry'
        required: true
runs:
    using: 'composite'
    steps:
        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/registry-login@main
          with:
            registry-name: ${{ inputs.registry_name }}
            github-user-name: ${{ inputs.github-user-name }}
            github-user-token: ${{ inputs.github-user-token }}

        - name: Stand up the devcontainer
          shell: bash
          run: |
            devcontainer up --workspace-folder ${PWD}
            echo ""
            echo "Directory structure"
            ls ${PWD}