name: 'stand-up-dev-container'
description:  'This stands up the devcontainer'
inputs:
    workspace-folder:
        description: 'The workspace folder'
        default: "${PWD}"
runs:
    using: 'composite'
    steps:
        - name: Stand up the devcontainer
          shell: bash
          run: |
            devcontainer up --workspace-folder ${{ inputs.workspace-folder }} \
                --workspace-mount-consistency cached \
                --id-label devcontainer.local_folder=${{ inputs.workspace-folder }} \
                --default-user-env-probe loginInteractiveShell \
                --build-no-cache \
                --remove-existing-container \
                --mount type=volume,source=vscode,target=/vscode,external=true \
                --update-remote-user-uid-default on \
                --mount-workspace-git-root true
            echo $?