name: 'install-regctl'
description:  'Installs regctl'
inputs:
    regctl_version:
        description: 'The version of regctl to install'
        default: 'v0.5.7'
runs:
    using: 'composite'
    steps:
        - name: Install RegCtl
          run: |
            VER_REGCTL=${{ inputs.regctl_version }}
            echo "Installing regctl - version ${VER_REGCTL}..."
            curl -L https://github.com/regclient/regclient/releases/download/${VER_REGCTL}/regctl-linux-amd64 >regctl
            sudo mv regctl /usr/local/bin/
            sudo chmod 755 /usr/local/bin/regctl
            rm -rf regctl
            echo "Getting Version Information"
            regctl version