name: 'run-push-build-artifact'
description:  'Runs the push_build)artifacts.sh for a single artifact'
inputs:
    env-file:
        description: 'Path to the env file'
        default: /var/spacedev/env/spacefx.env
    artifact:
        description: 'Path to the artifact to push'
        required: true
    architecture:
        description: 'The architecture for the image'
        required: true
    annotation-config:
        description: "The config file for the annotation"
    
runs:
    using: 'composite'
    steps:
        - name: Check if actor is approved
          shell: bash
          run: |
            approved_users="${{ secrets.WRITE_USERS }}"
            actor="${{ github.actor }}"
            if [[ ! " $approved_users " =~ " $actor " ]]; then
              echo "Error: $actor is not authorized to push artifacts. Please contact Azure Space SDK team for approval to push artifacts."
              exit 1
            fi

        - name: Push Artifact ${{ inputs.artifact }}
          shell: bash
          run: |
            source ${{ inputs.env-file }}

            echo "Running  bash ${SPACEFX_DIR}/build/push_build_artifact.sh --artifact ${{ inputs.artifact }}) --architecture ${{ inputs.architecture }} --artifact-version ${SPACEFX_VERSION}"

            bash ${SPACEFX_DIR}/build/push_build_artifact.sh --artifact ${{ inputs.artifact }} --architecture ${{ inputs.architecture }} --artifact-version ${SPACEFX_VERSION}
