name: 'Initialize'
description:  'Initializes the space sdk by setting up the /var/spacedev/directory'
inputs:
    env_file:
        description: 'The path to the environment file'
        required: false
        default: "/var/spacedev/env/spacefx.env"
    REGISTRY: 
        description: 'Registry to push the image to'
        type: string 
        default: 'ghcr.io/microsoft'
    VER_DOCKER_MAX:
        description: 'Docker version to install'
        required: false
        type: string
        default: "26.1.3"
    GIT_HUB_USER_NAME:
        description: 'The github user name'
        required: true
    GIT_HUB_USER_TOKEN:
        description: 'The github user token'
        required: true
    SETUP_REPO_URL:
        description: 'The setup repo url'
        required: true
runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v2

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/get-agent-details@main

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-docker@main
          with:
            VER_DOCKER_MAX: ${{ inputs.VER_DOCKER_MAX }}

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/get-setup@main
          with: 
            setup-repo-url: ${{ inputs.SETUP_REPO_URL }}

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-regctl@main
          with:
            env_file: ${{ inputs.env_file }}
        
        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@km/add_build_app

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-oras@main

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/registry-login@main
          with:
            registry-name: ${{ inputs.REGISTRY }}
            github-user-name: ${{ inputs.GIT_HUB_USER_NAME }}
            github-user-token: ${{ inputs.GIT_HUB_USER_TOKEN }}