name: 'Initialize'
description:  'Initializes the space sdk by setting up the /var/spacedev/directory'
inputs:
    env_file:
        description: 'The path to the environment file'
        required: true
    registry_name:
        description: 'The name of the registry'
        default: 'ghcr.io/microsoft/ao-spacesdk'
    token:
        description: 'The token to use for the registry'
        required: true
outputs:
    spacesdk_directory:
        description: 'The path to the spacesdk directory'
        value: '/var/spacedev'
runs:
    using: 'composite'
    steps:
        - uses: actions/composite-actions/install-regctl@km/add_structure
          with:
            env_file: ${{ inputs.env_file }}
        
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ inputs.registry_name }}
            username: ${{ github.actor }}
            password: ${{ inputs.token }}