name: 'clone-setup'
description:  'Clone setup and run stage space sdk'
inputs:
    setup-repo-url:
        description: 'The repo url to clone'
        default: 'ghcr.io/microsoft'
runs:
    using: 'composite'
    steps:
        - name: Clone repo
          shell: bash
          run: |
            mkdir -p /var/tmp
            cd /var/tmp
            git clone ${{ inputs.setup-repo-url }}
            cd azure-orbital-space-sdk-setup

        - name: Checkout branch and Copy to /var/spacedev
          shell: bash
          run: |
            cd /var/tmp/azure-orbital-space-sdk-setup

            # Extract the branch name from ACTION_REF
            echo "${ACTION_REF}" 
            BRANCH_REF=$(echo "${ACTION_REF}" | sed 's|refs/heads/||; s|refs/tags/||')

            echo "Detected Branch reference: ${BRANCH_REF}"
            echo "Checking out azure-orbital-space-sdk-setup under branch ${BRANCH_REF}"
            git checkout ${BRANCH_REF}
             
            bash ./.vscode/copy_to_spacedev.sh