name: 'clone-setup'
description:  'Clone setup and run stage space sdk'
inputs:
    setup-repo-url:
        description: 'The repo url to clone'
        default: 'ghcr.io/microsoft'
runs:
    using: 'composite'
    steps:
        - name: Clone repo
          shell: bash
          run: |
            mkdir -p /var/tmp
            cd /var/tmp
            git clone ${{ inputs.setup-repo-url }}
            cd azure-orbital-space-sdk-setup
          
        - name: Checkout branch and Copy to /var/spacedev
          shell: bash
          run: |
            cd /var/tmp/azure-orbital-space-sdk-setup

            # Extract composite action branch using parameter expansion
            echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
            EXTRACTED_PART=${GITHUB_ACTION_PATH#*/home/runner/work/_actions/microsoft/azure-orbital-space-sdk-github-actions/}
            BRANCH_REF=${EXTRACTED_PART%/composite-actions/get-setup}

            echo "Detected Branch reference: ${BRANCH_REF}"
            echo "Checking out azure-orbital-space-sdk-setup under branch ${BRANCH_REF}"
            git checkout ${BRANCH_REF}
             
            bash ./.vscode/copy_to_spacedev.sh