name: 'clone-setup'
description:  'Clone setup and run stage space sdk'
inputs:
    setup-repo-url:
        description: 'The repo url to clone'
        default: 'ghcr.io/microsoft'
runs:
    using: 'composite'
    steps:
        - name: Clone repo
          shell: bash
          run: |
            mkdir -p /var/tmp
            cd /var/tmp
            git clone ${{ inputs.setup-repo-url }}
            cd azure-orbital-space-sdk-setup

        - name: environment variables
          shell: bash
          run: |
            printenv
          
        - name: Checkout branch and Copy to /var/spacedev
          shell: bash
          run: |
            cd /var/tmp/azure-orbital-space-sdk-setup

            echo "Detected Branch reference: ${GITHUB_HEAD_REF}"
            echo "Checking out azure-orbital-space-sdk-setup under branch ${GITHUB_HEAD_REF}"
            git checkout ${GITHUB_HEAD_REF}
             
            bash ./.vscode/copy_to_spacedev.sh