name: Create Nightly Branchs

on:
  workflow_call:
    inputs:
      SPACEFX_VERSION:
        description: 'version of the Space SDK to label the nightly branch with'
        required: true
        type: string
        default: '0.11.0'
    secrets:
        GIT_HUB_USER_NAME:
            required: true
        GIT_HUB_USER_TOKEN:
            required: true
        REPO_URLS:
            required: true

jobs:

  create-nightly-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJSON(secrets.REPO_URLS) }}

    steps:
      - name: Checkout repository
        shell: bash
        run: |
          mkdir -p /var/tmp
          cd /var/tmp
          git clone ${{ matrix.repo }} repo
          cd repo


      - name: Create new branch
        shell: bash
        run: |
          cd /var/tmp/repo
          git checkout main
          git checkout -b "${{ inputs.SPACEFX_VERSION }}-nightly"

      - name: Push new branch to GitHub
        shell: bash
        run: |
          cd /var/tmp/repo
          git push origin "${{ inputs.SPACEFX_VERSION }}-nightly"
        env:
          GITHUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}