name: Echo Input

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Input provided by the user'
        required: true
        type: string

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the user input
        shell: bash
        run: |
            echo "User input: ${{ github.event.inputs.user_input }}"