name: Shared- plugin-build workflow
on:
    workflow_call:
        inputs:
            APP_PROJECT:
              description: 'The project to build'
              required: true
              type: string
            NUGET_PROJECT:
              description: 'The nuget project to build'
              type: string
            OUTPUT_DIR:
              description: 'The output directory for the build'
              required: true
              type: string
            PLUGIN_STAGING_DIRECTORY:
              description: 'The staging directory for the nuget packages'
              required: true
              type: string
            PLUGIN_FILE_NAME:
              description: 'The prefix for the nuget file'
              required: true
              type: string
            PLUGIN_CONFIG_FILE_NAME:
              description: 'The config file for the plugin'
              required: true
              type: string
            ANNOTATION:
              description: 'Annotation file'
              required: true
              type: string
            WORKFLOW_AGENT:
              description: 'The name of the workflow agent'
              type: string
              default: 'ubuntu-latest'
            ARCHITECTURE:
              description: 'The architecture for the image'
              required: true
              type: string
            SPACESDK_VERSION:
              description: 'The version of the space sdk'
              type: string
              default: "0.11.0"
            DEV_CONTAINER_JSON:
              description: 'The dev container json file'
              type: string
            PROTO_STAGING_DIRECTORY:
              required: false
              default: ''
              description: 'Destination directory for the proto file'
              type: string
            PROTO_FOLDER_PATH:
              required: false
              default: ''
              description: 'Source directory with the proto file'
              type: string
            PROTO_FILE_NAME:
              required: false
              default: ''
              description: 'Name of the proto file'
              type: string
        secrets:
            GIT_HUB_USER_NAME:
                required: true
            GIT_HUB_USER_TOKEN:
                required: true
            SETUP_REPO_URL:
                required: true

jobs:
  build-plugin:
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    permissions:
      contents: read
      packages: write

    steps:
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@main
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/build-app@main
      with:
        ARCHITECTURE: ${{ inputs.ARCHITECTURE }}
        APP_PROJECT: ${{ inputs.APP_PROJECT}}
        APP_VERSION: ${{ inputs.SPACESDK_VERSION }}
        OUTPUT_DIR: ${{ inputs.OUTPUT_DIR }}
        ANNOTATION_CONFIG: ${{ inputs.ANNOTATION}}
        NO_CONTAINER_BUILD: 'false'
        DEV_CONTAINER_JSON: ${{ inputs.DEV_CONTAINER_JSON }}

    - name: Move file to staging directory
      shell: bash
      run: |
        sudo mkdir -p ${{ inputs.PLUGIN_STAGING_DIRECTORY }}

        sudo cp ${{ inputs.OUTPUT_DIR }}/${{ inputs.ARCHITECTURE }}/app/${{ inputs.PLUGIN_FILE_NAME }} ${{ inputs.PLUGIN_STAGING_DIRECTORY }}
        sudo cp ${{ inputs.OUTPUT_DIR }}/${{ inputs.ARCHITECTURE }}/app/${{ inputs.PLUGIN_CONFIG_FILE_NAME }} ${{ inputs.PLUGIN_STAGING_DIRECTORY }}
        tree ${{ inputs.PLUGIN_STAGING_DIRECTORY }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@main
      with:
        artifact: ${{ inputs.PLUGIN_STAGING_DIRECTORY }}/${{ inputs.PLUGIN_FILE_NAME }}
        architecture: ${{ inputs.ARCHITECTURE }}
        annotation-config: ${{ inputs.ANNOTATION }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@main
      with:
        artifact: ${{ inputs.PLUGIN_STAGING_DIRECTORY }}/${{ inputs.PLUGIN_CONFIG_FILE_NAME }}
        architecture: ${{ inputs.ARCHITECTURE }}
        annotation-config: ${{ inputs.ANNOTATION }}

    - name: Move protos to staging directory
      if: inputs.PROTO_STAGING_DIRECTORY != ''
      shell: bash
      run: |
        sudo mkdir -p ${{ inputs.PROTO_STAGING_DIRECTORY }}
        sudo cp ${{ inputs.PROTO_FOLDER_PATH }}/${{ inputs.PROTO_FILE_NAME }} ${{ inputs.PROTO_STAGING_DIRECTORY }} || echo "No proto files to move"

        tree ${{ inputs.PROTO_STAGING_DIRECTORY }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@main
      if: inputs.PROTO_STAGING_DIRECTORY != ''
      with:
        artifact: ${{ inputs.PROTO_STAGING_DIRECTORY }}/${{ inputs.PROTO_FILE_NAME }}
        architecture: ${{ inputs.ARCHITECTURE }}