on: 
    workflow_call:
      inputs:
        artifact:
          description: 'The path to the artifact that will be pushed'
          required: true
          type: string
        env-file:
            description: 'Path to the env file'
            default: /var/spacedev/env/spacefx.env
            type: string
      secrets:
        GIT_HUB_USER_NAME:
            required: true
        GIT_HUB_USER_TOKEN:
            required: true
        SETUP_REPO_URL:
            required: true

jobs:
  test-install-regctl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@main
      with:
          env_file: ./env/spacefx.env
          GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
          GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
          SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}
          VER_DOCKER_MAX: ${{ inputs.VER_DOCKER_MAX }}
  
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@al/push_build_artifacts
      with:
        artifact: ${{ inputs.artifact }}
        architecture: "amd64"

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@al/push_build_artifacts
      with:
        artifact: ${{ inputs.artifact }}
        architecture: "arm64"


    - name: Validate Artifact
      shell: bash
      run: |
        oras pull ghcr.io/microsoft/buildartifacts/push-build-artifact-test:0.10.0
        cat push-build-artifact-test.txt

    
        