name: test initialize
on: 
    workflow_call:
      inputs:
        WORKFLOW_AGENT:
          description: 'The agent to run the job on'
          required: true
          type: string
      secrets:
        GIT_HUB_USER_NAME:
          description: 'The github user name'
          required: true
        GIT_HUB_USER_TOKEN:
          description: 'The github user token'
          required: true
        SETUP_REPO_URL:
          description: 'The setup repo url'
          required: true

jobs:
  test-capture-logs:
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@0.11.0-nightly
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - name: Create file
      shell: bash
      run: |
        sudo mkdir -p /var/spacedev/logs 
        sudo chown -R $USER:$USER /var/spacedev
        sudo echo "Hello World" > /var/spacedev/logs/hello.txt

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/capture-logs@al/update-upload-artifact
      with:
        ARTIFACT_NAME: 'var-spacedev-logs'
        DIRECTORY_PATH: '/var/spacedev/logs/**'