name: test get agent details
on: 
    workflow_call:
      inputs:
        agent:
          description: 'The agent to run the job on'
          required: true
          type: string

jobs:
  test-get-agent-details:
    runs-on: ${{ inputs.agent }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/get-agent-details@main