on: 
    workflow_call:
      inputs:
        env_file:
          description: 'The path to the environment file'
          required: true
          type: string

jobs:
  test-install-regctl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-docker@km/add_docker
      with:
        env_file: ${{ inputs.env_file }}

    - name: Validate docker
      shell: bash
      run: |
        source ${{ inputs.env_file }}

        VERSION_COMMAND_OUTPUT=$(docker version)
        INSTALLED_VER=$(echo "$VERSION_COMMAND_OUTPUT" | awk '/Version:/{print $2; exit}')

        # Compare the installed version with the required version
        if [ "$INSTALLED_VER" == "$VER_DOCKER_MIN" ]; then
            echo "Version matches"
        else
            echo "Version does not match. Installed version is $INSTALLED_VER but required version is $VER_REGCTL"
            exit 1
        fi