name: Test Application
on: 
    workflow_call:
        inputs:
            APP_NAME:
              description: 'The name of the hostsvc or platformsvc to test'
              required: true
              type: string
            WORKFLOW_AGENT:
              description: 'The name of the workflow agent'
              type: string
              default: 'ubuntu-latest'
        secrets:
            GIT_HUB_USER_NAME:
                required: true
            GIT_HUB_USER_TOKEN:
                required: true
            SETUP_REPO_URL:
                required: true

jobs:
  test-application:
    name: "Test ${{ inputs.APP_NAME }} - ${{ inputs.WORKFLOW_AGENT}}"
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@main
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - name: Install Extra Dependencies
      if: inputs.WORKFLOW_AGENT == 'spacesdk-ubuntu-2204LTS-arm64'
      shell: bash
      run: |
        echo "Installing extra dependencies for spacesdk-ubuntu-2204LTS-arm64"
        sudo apt install -y python3.10-venv
        sudo apt install -y python3-pip-whl
        sudo apt install -y python3-setuptools-whl
        sudo apt-get install -y gcc python3-dev

        
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/test-app@main
      with:
        APP_NAME: ${{ inputs.APP_NAME }}