on: 
    workflow_call:

env: 
  env_file: ./test-artifacts/test-install-regctl/test.env

jobs:
  test-install-regctl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-regctl@main
      with:
        env_file: ${{ env.env_file }}

    - name: Validate regctl
      shell: bash
      run: |
        source ${{ env.env_file }}

        INSTALLED_VER=$(regctl version)

        # Compare the installed version with the required version
        if [ "$INSTALLED_VER" == "$VER_REGCTL" ]; then
            echo "Version matches"
        else
            echo "Version does not match. Installed version is $INSTALLED_VER but required version is $VER_REGCTL"
            exit 1
        fi
        