on: 
    workflow_call:
      inputs:
        artifact:
          description: 'The path to the artifact that will be pushed'
          required: true
          type: string
        env-file:
            description: 'Path to the env file'
            default: /var/spacedev/env/spacefx.env
            type: string
        architecture:
            description: 'Path to the env file'
            required: true
            type: string
        WORKFLOW_AGENT:
          description: 'The agent to run the job on'
          required: true
          type: string
      secrets:
        GIT_HUB_USER_NAME:
            required: true
        GIT_HUB_USER_TOKEN:
            required: true
        SETUP_REPO_URL:
            required: true

jobs:
  test-push-build-artifact:
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@0.11.0-nightly
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-helm@0.11.0-nightly
  
    - name: Move file to staging directory
      shell: bash
      run: |
        mkdir -p /var/spacedev/test
        sudo mv ${{ inputs.artifact }} /var/spacedev/test
        tree /var/spacedev/test

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@0.11.0-nightly
      with:
        artifact: "/var/spacedev/test/push-build-artifact-test.txt"
        architecture: "${{ inputs.architecture }}"

    - name: Validate Artifact
      shell: bash
      run: |
        source ${{ inputs.env-file }}
        filename=$(basename "${{ inputs.artifact }}" .txt)
        echo "Executing: ghcr.io/microsoft/azure-orbital-space-sdk/buildartifacts/txt/${filename} --output ${PWD} --filter-artifact-type application/vnd.spacefx.${{ inputs.architecture }}}.buildartifact"

        regctl ghcr.io/microsoft/azure-orbital-space-sdk/buildartifacts/txt/${filename} --output ${PWD} --filter-artifact-type application/vnd.spacefx.${{ inputs.architecture }}}.buildartifact
        
        echo "Outputing contents of ghcr.io/microsoft/azure-orbital-space-sdk/buildartifacts/txt/${filename}:${SPACEFX_VERSION}-nightly"
        cat push-build-artifact-test.txt