name: Test Application
on: 
    workflow_call:
        inputs:
            APP_NAME:
              description: 'The name of the hostsvc or platformsvc to test'
              required: true
              type: string
            WORKFLOW_AGENT:
              description: 'The name of the workflow agent'
              type: string
              default: 'ubuntu-latest'
            SMB_ON:
              description: 'Whether to switch on SMB or not'
              type: string
              default: 'false'
        secrets:
            GIT_HUB_USER_NAME:
                required: true
            GIT_HUB_USER_TOKEN:
                required: true
            SETUP_REPO_URL:
                required: true

jobs:
  test-application:
    name: "Test ${{ inputs.APP_NAME }} - ${{ inputs.WORKFLOW_AGENT}}"
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@0.11.0-nightly
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/switch-smb@0.11.0-nightly
      if: inputs.SMB_ON == 'true'
      with:
        REPO_DIR: "${PWD}"
        VALUE: "true"

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-publish-dependencies@0.11.0-nightly
      if: inputs.WORKFLOW_AGENT == 'spacesdk-ubuntu-2204LTS-arm64'

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/test-app@0.11.0-nightly
      with:
        APP_NAME: ${{ inputs.APP_NAME }}