name: Test-installing devcontainer cli
on: 
    workflow_call:
      inputs:
        agent:
          description: 'The agent to run the job on'
          required: true
          type: string

jobs:
  test-install-devcontainer-cli:
    runs-on: ${{ inputs.agent }}

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@km/add_docker

    - name: Validate devcontainer cli
      shell: bash
      run: |
        if command -v devcontainer &> /dev/null
        then
            echo "devcontainer CLI is installed"
        else
            echo "devcontainer CLI is not installed"
            exit 1
        fi