on: workflow_call

jobs:
  test-install-devcontainer-cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@main

    - name: Validate Devcontainer stool installed correctly
      shell: bash
      run: |
        devcontainer --help
