on: workflow_call

jobs:
  test-install-devcontainer-cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@0.11.0-nightly

    - name: Validate Devcontainer stool installed correctly
      shell: bash
      run: |
        devcontainer --help
