name: Test Plugin
on: 
    workflow_call:
        inputs:
            APP_NAME:
              description: 'The name of the hostsvc or platformsvc to the plugin is built for'
              type: string
              required: true
            PLUGIN_NAME:
              description: 'The name of the plugin to test'
              type: string
              required: true
            DEVCONTAINER_JSON:
              description: 'The dev container json file'
              type: string
              required: true
            REPO_DIR:
              description: 'The directory of the plugin repo'
              type: string
              required: true
            TEST_PROJECT:
              description: 'Relative path to the test project to run'
              type: string
              default: "test/integrationTests/integrationTests.csproj"
            WORKFLOW_AGENT:
              description: 'The name of the workflow agent'
              type: string
              default: 'ubuntu-latest'
            SMB_ON:
              description: 'Whether to switch on SMB or not'
              type: string
              default: 'false'
        secrets:
            GIT_HUB_USER_NAME:
                required: true
            GIT_HUB_USER_TOKEN:
                required: true
            SETUP_REPO_URL:
                required: true

jobs:
  test-application:
    name: "Test ${{ inputs.PLUGIN_NAME }} - ${{ inputs.WORKFLOW_AGENT}}"
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@main
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/switch-smb@main
      if: inputs.SMB_ON == 'true'
      with:
        REPO_DIR: "${PWD}"
        VALUE: "true"

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-publish-dependencies@main
      if: inputs.WORKFLOW_AGENT == 'spacesdk-ubuntu-2204LTS-arm64'

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/test-plugin@al/test-plugin-workflow
      with:
        APP_NAME: ${{ inputs.APP_NAME }}
        PLUGIN_NAME: ${{ inputs.PLUGIN_NAME }}
        TEST_PROJECT: ${{ inputs.TEST_PROJECT }}
        DEVCONTAINER_JSON: ${{ inputs.DEVCONTAINER_JSON }}
        REPO_DIR: ${{ inputs.REPO_DIR }}
