on: 
    workflow_call:
      inputs:
        artifact:
          description: 'The path to the artifact that will be pushed'
          required: true
          type: string
        env-file:
            description: 'Path to the env file'
            default: /var/spacedev/env/spacefx.env
            type: string

jobs:
  test-install-regctl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-regctl@al/push_build_artifacts
      with:
        env_file: ${{ inputs.env_file }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-oras@al/push_build_artifacts
      with:
        oras_version: 0.16.0

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/registry-login@al/push_build_artifacts
      with:
        registry-name: ${{ inputs.REGISTRY }}
        github-user-name: ${{ secrets.GIT_HUB_USER_NAME }}
        github-user-token: ${{ secrets.GIT_HUB_USER_TOKEN }}
  
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/get-setup@al/push_build_artifacts
      with: 
        setup-repo-url: ${{ secrets.SETUP_REPO_URL }}
  
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifacts@al/push_build_artifacts
      with:
        artifact: ${{ inputs.artifact }}
        architecture: "amd64"

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifacts@al/push_build_artifacts
      with:
        artifact: ${{ inputs.artifact }}
        architecture: "arm64"


    - name: Validate Artifact
      shell: bash
      run: |
        oras pull ghcr.io/microsoft/buildartifacts/push-build-artifact-test:0.10.0
        cat push-build-artifact-test.txt

    
        