on: workflow_call

jobs:
  test-install-devcontainer-cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@main

    - name: Validate Devcontainer stool installed correctly
      shell: bash
      run: |
        devcontainer --help
